CREATE TABLE IF NOT EXISTS sys_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entry_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    total_chicks INT NOT NULL,
    entry_date DATE NOT NULL,
    breed VARCHAR(100) NOT NULL,
    price_per_chick DECIMAL(10, 2) NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS breeding_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    record_date DATE NOT NULL,
    avg_weight DECIMAL(10, 2) NOT NULL,
    dead_count INT NOT NULL DEFAULT 0,
    survival_count INT NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, record_date),
    FOREIGN KEY (user_id) REFERENCES sys_user(id)
);

CREATE TABLE IF NOT EXISTS cost_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    record_date DATE NOT NULL,
    category VARCHAR(20) NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    remark VARCHAR(255),
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES sys_user(id)
);

CREATE INDEX IF NOT EXISTS idx_cost_date ON cost_record(record_date);
CREATE INDEX IF NOT EXISTS idx_cost_category ON cost_record(category);
CREATE INDEX IF NOT EXISTS idx_entry_user ON entry_record(user_id);
CREATE INDEX IF NOT EXISTS idx_breeding_user ON breeding_status(user_id);
CREATE INDEX IF NOT EXISTS idx_cost_user ON cost_record(user_id);
